[package]
name = "iroh-car"
version = "0.1.0-vendored.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation the car files for iroh"

[dependencies]
cid = "*"
ipld = { package = "libipld", version = "0.14"}
ipld-cbor = { package = "libipld-cbor", version = "0.14" }
thiserror = "1.0"
futures = "0.3"
integer-encoding = { version = "3", features = ["tokio_async"] }
multihash = "0.16"
tokio = { version = "1", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "sync", "rt", "fs", "io-util"] }

[features]
