[package]
name = "adenosine-pds"
version = "0.1.0-dev.0"
edition = "2021"
authors = ["Bryan Newbold <bnewbold@robocracy.org>"]
license = "AGPLv3"
description = "Informal implementation of atproto.com"
readme = "../README.md"
repository = "https://gitlab.com/bnewbold/adenosine"
keywords = ["atproto"]
#categories = []

[dependencies]
structopt = "*"
hyper = "*"
tokio = { version = "1", features = ["full"] }
serde_json = "*"
log = "*"
env_logger = "*"

[package.metadata.deb]
maintainer = "Bryan Newbold <bnewbold@robocracy.org>"
depends = "$auto"
section = "utility"
priority = "optional"
extended-description = """"TODO"""
assets = [
    ["target/release/adenosine-pds", "usr/bin/", "755"],
    #["../extra/adenosine-pds.1", "usr/share/man/man1/", "644"],
]
