[package]
name = "adenosine-pds"
description = "Simple informal personal data server (PDS) for AT protocol and bsky.app"
keywords = ["atproto"]
categories = []

version = "0.1.0-dev.0"
edition = "2021"
rust-version = "1.61"
authors = ["Bryan Newbold <bnewbold@robocracy.org>"]
license = "AGPLv3"
readme = "../README.md"
repository = "https://gitlab.com/bnewbold/adenosine"

[dependencies]
anyhow = "*"
structopt = "*"
serde = "1"
serde_json = "*"
log = "*"
pretty_env_logger = "*"
libipld = "*"
ipfs-sqlite-block-store = "*"
rusqlite = { version = "*", features = ["bundled"] }
rusqlite_migration = "*"
jsonschema = "*"
schemafy = "*"
rouille = "*"
# NOTE: vendored for now
#iroh-car = "*"
adenosine-cli = { version = "0.1.0-dev.0", path = "../adenosine-cli" }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
sha256 = "*"
lazy_static = "*"
bcrypt = "0.13"
data-encoding = "*"
k256 = { version = "*", features = ["ecdsa"] }
p256 = { version = "*", features = ["ecdsa"] }
multibase = "*"
ucan = "0.7.0-alpha.1"
# TODO: replace this with data-encoding or similar; this is only needed for ucan_p256 stuff
bs58 = "*"
async-trait = "*"
dotenv = "*"
askama = { version = "0.11", features = ["serde-json"] }
time = { version = "*", features = ["formatting"] }

# for vendored iroh-car
thiserror = "1.0"
integer-encoding = { version = "3", features = ["tokio_async"] }
multihash = "0.16"

[package.metadata.deb]
maintainer = "Bryan Newbold <bnewbold@robocracy.org>"
depends = "$auto"
section = "utility"
priority = "optional"
extended-description = """Simple informal personal data server (PDS) for AT protocol and bsky.app"""
assets = [
    ["target/release/adenosine-pds", "usr/bin/", "755"],
    #["../extra/adenosine-pds.1", "usr/share/man/man1/", "644"],
]
