[workspace]
members = ["adenosine-cli", "adenosine-tauri-gui", "adenosine-pds"]

# NOTE: [workspace.package] did not work with some plugins and build tools

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
