[package]
name = "adenosine-cli"
version = "0.1.0-dev.0"
edition = "2021"
authors = ["Bryan Newbold <bnewbold@robocracy.org>"]
license = "AGPLv3"
description = "Informal implementation of atproto.com"
readme = "../README.md"
repository = "https://gitlab.com/bnewbold/adenosine"
keywords = ["atproto"]
#categories = []

[dependencies]
structopt = "*"
# NOTE: could try 'rustls-tls' feature instead of default native TLS?
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "*"
base64 = "*"

# uncertain about these...
anyhow = "1.0"
atty = "0.2"
colored_json = "*"
termcolor = "*"
log = "*"
env_logger = "*"

[package.metadata.deb]
maintainer = "Bryan Newbold <bnewbold@robocracy.org>"
depends = "$auto"
section = "utility"
priority = "optional"
extended-description = """"TODO"""
assets = [
    ["target/release/adenosine", "usr/bin/", "755"],
    #["../extra/adenosine.1", "usr/share/man/man1/", "644"],
]
